### ISSUE TITLE
Subtask - Create API Endpoints

### ISSUE THREAD

**Issue by ChoEjik** [SocialFinanceDigitalLabs/sf-fons-platform#78]
This Task is completed when: 

The following API endpoints are fully functioning -

a. List Files Endpoint (REST GET)
- [ ] -  Create a view to handle the list-files endpoint.
- [ ] -  Implement logic to descend into the S3 file tree and return a flattened list of files.
- [ ] -  Add pagination, sorting, and filtering (if necessary).

b. Get File Endpoint (REST GET)
- [ ]  Create a view to handle the get-file endpoint.
- [ ]  Implement logic to retrieve and return the file body as a download.
- [ ]  Ensure that URLs are formed against the Django URL, not S3.
- [ ]  Implement permission checks/logic to ensure users can only download permitted files.

c. Delete File Endpoint (REST DELETE)
- [ ] -  Create a view to handle the delete-file endpoint.
- [ ] -  Implement logic to delete the file from S3.
- [ ] -  Implement permission checks/logic to ensure users can only delete permitted files.
