### ISSUE TITLE
Subtask - Create new Django app within existing project.

### ISSUE THREAD

**Issue by ChoEjik** [SocialFinanceDigitalLabs/sf-fons-platform#79]
Create Django App

- [ ] Create a new Django app within the existing project (e.g., file_proxy).
- [ ] Add the app to the INSTALLED_APPS in the Django settings.
- [ ] Define Models (if necessary)
- [ ] Set Up File Storage Backend
- [ ] Configure Django to use pyfilesystem for interacting with the S3 storage.
