### ISSUE TITLE
Subtask - implement testing for new Django API 

### ISSUE THREAD

**Issue by ChoEjik** [SocialFinanceDigitalLabs/sf-fons-platform#85]
- [ ]  Write unit tests for each endpoint to ensure they function correctly.
- [ ]  Write integration tests to ensure the overall flow works as expected.
- [ ]  Test permission checks to ensure users can only perform allowed actions.
- [ ]  Test user flow with front end to ensure seamless experience.
